SET(SOURCES ui_Screen0.c
    ui_Screen1.c
    ui_Screen2.c
    ui_Screen3.c
    ui_Screen4.c
    ui.c
    ui_comp_hook.c
    ui_helpers.c
    ui_img_power_on_progress_01_png.c
    ui_img_power_on_light_400_250707_png.c
    ui_img_1871529928.c
    ui_img_829316181.c
    ui_img_1854458106.c
    ui_img_573924602.c
    ui_img_1735368907.c
    ui_img_2001748219.c
    ui_img_32356014.c
    ui_img_667923968.c
    ui_img_1761703117.c
    ui_img_175727810.c
    ui_img_1961151970.c
    ui_img_247193628.c
    ui_img_v2_bj_temp_png.c
    ui_img_2125542142.c
    ui_img_1643306962.c
    ui_img_1734024440.c
    ui_img_1741863219.c
    ui_img_1212264740.c)

add_library(ui ${SOURCES})
