// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 9.1.0
// Project name: SLS480v2

#ifndef _SLS480V2_UI_H
#define _SLS480V2_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"

void progress_Animation(lv_obj_t * TargetObject, int delay);

// SCREEN: ui_Screen0
void ui_Screen0_screen_init(void);
void ui_event_Screen0(lv_event_t * e);
extern lv_obj_t * ui_Screen0;
extern lv_obj_t * ui_progress;
extern lv_obj_t * ui_Image4;
// CUSTOM VARIABLES

// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_volumeWhite;
extern lv_obj_t * ui_volumeTextWhite;
void ui_event_volumeBlue(lv_event_t * e);
extern lv_obj_t * ui_volumeBlue;
void ui_event_tempBlue(lv_event_t * e);
extern lv_obj_t * ui_tempBlue;
extern lv_obj_t * ui_tempWhite;
extern lv_obj_t * ui_s1select;
extern lv_obj_t * ui_volumeTextBlue;
extern lv_obj_t * ui_tempTextBlue;
extern lv_obj_t * ui_tempTextWhite;
extern lv_obj_t * ui_lightWhite;
extern lv_obj_t * ui_lightTextWhite;
void ui_event_lightBlue(lv_event_t * e);
extern lv_obj_t * ui_lightBlue;
extern lv_obj_t * ui_lightTextBlue;
// CUSTOM VARIABLES

// SCREEN: ui_Screen2
void ui_Screen2_screen_init(void);
extern lv_obj_t * ui_Screen2;
extern lv_obj_t * ui_VolumeArc;
extern lv_obj_t * ui_Image1;
extern lv_obj_t * ui_VolNum;
extern lv_obj_t * ui_Label2;
void ui_event_screen2ReturnBt(lv_event_t * e);
extern lv_obj_t * ui_screen2ReturnBt;
extern lv_obj_t * ui_Label3;
extern lv_obj_t * ui_Button8;
extern lv_obj_t * ui_Button9;
extern lv_obj_t * ui_Button10;
extern lv_obj_t * ui_Button14;
extern lv_obj_t * ui_Button15;
extern lv_obj_t * ui_Button16;
// CUSTOM VARIABLES

// SCREEN: ui_Screen3
void ui_Screen3_screen_init(void);
extern lv_obj_t * ui_Screen3;
extern lv_obj_t * ui_TempArc;
extern lv_obj_t * ui_Image2;
extern lv_obj_t * ui_TempNum;
extern lv_obj_t * ui_Label1;
void ui_event_screen3ReturnBt(lv_event_t * e);
extern lv_obj_t * ui_screen3ReturnBt;
extern lv_obj_t * ui_Label4;
extern lv_obj_t * ui_Button1;
extern lv_obj_t * ui_Button2;
extern lv_obj_t * ui_Button3;
extern lv_obj_t * ui_Button11;
extern lv_obj_t * ui_Button12;
extern lv_obj_t * ui_Button13;
// CUSTOM VARIABLES

// SCREEN: ui_Screen4
void ui_Screen4_screen_init(void);
extern lv_obj_t * ui_Screen4;
extern lv_obj_t * ui_lightArc;
extern lv_obj_t * ui_Image3;
extern lv_obj_t * ui_LightNum;
extern lv_obj_t * ui_Label5;
void ui_event_screen4ReturnBt(lv_event_t * e);
extern lv_obj_t * ui_screen4ReturnBt;
extern lv_obj_t * ui_Label6;
extern lv_obj_t * ui_Button5;
extern lv_obj_t * ui_Button6;
extern lv_obj_t * ui_Button7;
extern lv_obj_t * ui_Button17;
extern lv_obj_t * ui_Button18;
extern lv_obj_t * ui_Button19;
// CUSTOM VARIABLES

// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_power_on_progress_01_png);    // assets/power_on_progress_01.png
LV_IMG_DECLARE(ui_img_power_on_light_400_250707_png);    // assets/power_on_light_400_250707.png
LV_IMG_DECLARE(ui_img_1871529928);    // assets/device_control_bj_01@2x.png
LV_IMG_DECLARE(ui_img_829316181);    // assets/icon_volume_601@2x.png
LV_IMG_DECLARE(ui_img_1854458106);    // assets/icon_volume_602@2x.png
LV_IMG_DECLARE(ui_img_573924602);    // assets/icon_temp_602@2x.png
LV_IMG_DECLARE(ui_img_1735368907);    // assets/icon_temp_601@2x.png
LV_IMG_DECLARE(ui_img_2001748219);    // assets/device_control_select_02@2x.png
LV_IMG_DECLARE(ui_img_32356014);    // assets/icon_light_601@3x(1).png
LV_IMG_DECLARE(ui_img_667923968);    // assets/icon_light_602@2x.png
LV_IMG_DECLARE(ui_img_1761703117);    // assets/v2_bj_volume_100@2x.png
LV_IMG_DECLARE(ui_img_175727810);    // assets/bar_white@2x.png
LV_IMG_DECLARE(ui_img_1961151970);    // assets/bar_bule_02@2x.png
LV_IMG_DECLARE(ui_img_247193628);    // assets/icon_volume_40@2x.png
LV_IMG_DECLARE(ui_img_v2_bj_temp_png);    // assets/v2_bj_temp.png
LV_IMG_DECLARE(ui_img_2125542142);    // assets/bar_blackbule@2x.png
LV_IMG_DECLARE(ui_img_1643306962);    // assets/bar_orange_02@2x.png
LV_IMG_DECLARE(ui_img_1734024440);    // assets/icon_temp_40@2x.png
LV_IMG_DECLARE(ui_img_1741863219);    // assets/v2_bj_light_100@2x.png
LV_IMG_DECLARE(ui_img_1212264740);    // assets/bar_yellow_02@2x.png

// UI INIT
void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
