// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.3
// Project name: SLS480v2

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////
void ani_rb1_Animation(lv_obj_t * TargetObject, int delay);
void ani_rb0_Animation(lv_obj_t * TargetObject, int delay);
void ani_gold_Animation(lv_obj_t * TargetObject, int delay);
void ani_reddot_Animation(lv_obj_t * TargetObject, int delay);


// SCREEN: ui_Screen0
void ui_Screen0_screen_init(void);
void ui_event_Screen0(lv_event_t * e);
lv_obj_t * ui_Screen0;
lv_obj_t * ui_s0rb1;
lv_obj_t * ui_s0rb0;
lv_obj_t * ui_s0brown;
lv_obj_t * ui_s0gold;


// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
lv_obj_t * ui_Screen1;
lv_obj_t * ui_s1select;
lv_obj_t * ui_s1volume1;
lv_obj_t * ui_s1volume2;
lv_obj_t * ui_s1lbvolume;
lv_obj_t * ui_s1temp1;
lv_obj_t * ui_s1temp2;
lv_obj_t * ui_s1lbtemp;
lv_obj_t * ui_s1light1;
lv_obj_t * ui_s1light2;
lv_obj_t * ui_s1lblight;


// SCREEN: ui_Screen2
void ui_Screen2_screen_init(void);
lv_obj_t * ui_Screen2;
void ui_event_s2btn1(lv_event_t * e);
lv_obj_t * ui_s2btn1;
lv_obj_t * ui_s2lbbtn1;
void ui_event_s2btn2(lv_event_t * e);
lv_obj_t * ui_s2btn2;
lv_obj_t * ui_s2lbbtn2;
void ui_event_s2btn3(lv_event_t * e);
lv_obj_t * ui_s2btn3;
lv_obj_t * ui_s2lbbtn3;
lv_obj_t * ui_s2Container;
lv_obj_t * ui_s2bar1;
lv_obj_t * ui_s2bar2;
lv_obj_t * ui_s2arc;
lv_obj_t * ui_s2icon;
lv_obj_t * ui_s2volume;
lv_obj_t * ui_s2num1;
lv_obj_t * ui_s2num2;
lv_obj_t * ui_s2num0;
lv_obj_t * ui_s2num10;
lv_obj_t * ui_s2num20;
lv_obj_t * ui_s2num30;
lv_obj_t * ui_s2num40;
lv_obj_t * ui_s2num50;
lv_obj_t * ui_s2num60;
lv_obj_t * ui_s2num70;
lv_obj_t * ui_s2num80;
lv_obj_t * ui_s2num90;
lv_obj_t * ui_s2num100;


// SCREEN: ui_Screen3
void ui_Screen3_screen_init(void);
lv_obj_t * ui_Screen3;
void ui_event_s3btn1(lv_event_t * e);
lv_obj_t * ui_s3btn1;
lv_obj_t * ui_s3lbbtn1;
void ui_event_s3btn2(lv_event_t * e);
lv_obj_t * ui_s3btn2;
lv_obj_t * ui_s3lbbtn2;
void ui_event_s3btn3(lv_event_t * e);
lv_obj_t * ui_s3btn3;
lv_obj_t * ui_s3lbbtn3;
lv_obj_t * ui_s3Container;
lv_obj_t * ui_s3bar1;
lv_obj_t * ui_s3bar2;
lv_obj_t * ui_s3arc;
lv_obj_t * ui_s3icon;
lv_obj_t * ui_s3temp;
lv_obj_t * ui_s3num1;
lv_obj_t * ui_s3num2;
lv_obj_t * ui_s3num0;
lv_obj_t * ui_s3num10;
lv_obj_t * ui_s3num20;
lv_obj_t * ui_s3num30;
lv_obj_t * ui_s3num40;
lv_obj_t * ui_s3num50;
lv_obj_t * ui_s3num60;
lv_obj_t * ui_s3num70;
lv_obj_t * ui_s3num80;
lv_obj_t * ui_s3num90;
lv_obj_t * ui_s3num100;


// SCREEN: ui_Screen4
void ui_Screen4_screen_init(void);
lv_obj_t * ui_Screen4;
void ui_event_s4btn1(lv_event_t * e);
lv_obj_t * ui_s4btn1;
lv_obj_t * ui_s4lbbtn1;
void ui_event_s4btn2(lv_event_t * e);
lv_obj_t * ui_s4btn2;
lv_obj_t * ui_s4lbbtn2;
void ui_event_s4btn3(lv_event_t * e);
lv_obj_t * ui_s4btn3;
lv_obj_t * ui_s4lbbtn3;
lv_obj_t * ui_s4Container;
lv_obj_t * ui_s4bar1;
lv_obj_t * ui_s4bar2;
lv_obj_t * ui_s4arc;
lv_obj_t * ui_s4icon;
lv_obj_t * ui_s4light;
lv_obj_t * ui_s4num1;
lv_obj_t * ui_s4num2;
lv_obj_t * ui_s4num0;
lv_obj_t * ui_s4num10;
lv_obj_t * ui_s4num20;
lv_obj_t * ui_s4num30;
lv_obj_t * ui_s4num40;
lv_obj_t * ui_s4num50;
lv_obj_t * ui_s4num60;
lv_obj_t * ui_s4num70;
lv_obj_t * ui_s4num80;
lv_obj_t * ui_s4num90;
lv_obj_t * ui_s4num100;
lv_obj_t * ui____initial_actions0;
const lv_img_dsc_t * ui_imgset_slight[2] = {&ui_img_to128_s1light1_png, &ui_img_s1light1_png};
const lv_img_dsc_t * ui_imgset_s1light[2] = {&ui_img_to128_s1light2_png, &ui_img_s1light2_png};
const lv_img_dsc_t * ui_imgset_stemp[2] = {&ui_img_to128_s1temp1_png, &ui_img_s1temp1_png};
const lv_img_dsc_t * ui_imgset_s1temp[2] = {&ui_img_to128_s1temp2_png, &ui_img_s1temp2_png};
const lv_img_dsc_t * ui_imgset_svolume[2] = {&ui_img_to128_s1volume1_png, &ui_img_s1volume1_png};
const lv_img_dsc_t * ui_imgset_s1volume[2] = {&ui_img_to128_s1volume2_png, &ui_img_s1volume2_png};
const lv_img_dsc_t * ui_imgset_srb[1] = {&ui_img_s0rb0_png};
const lv_img_dsc_t * ui_imgset_s0rb[1] = {&ui_img_s0rb1_png};

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////
void ani_rb1_Animation(lv_obj_t * TargetObject, int delay)
{
    ui_anim_user_data_t * PropertyAnimation_0_user_data = lv_mem_alloc(sizeof(ui_anim_user_data_t));
    PropertyAnimation_0_user_data->target = TargetObject;
    PropertyAnimation_0_user_data->val = -1;
    lv_anim_t PropertyAnimation_0;
    lv_anim_init(&PropertyAnimation_0);
    lv_anim_set_time(&PropertyAnimation_0, 1000);
    lv_anim_set_user_data(&PropertyAnimation_0, PropertyAnimation_0_user_data);
    lv_anim_set_custom_exec_cb(&PropertyAnimation_0, _ui_anim_callback_set_image_angle);
    lv_anim_set_values(&PropertyAnimation_0, 0, 3600);
    lv_anim_set_path_cb(&PropertyAnimation_0, lv_anim_path_linear);
    lv_anim_set_delay(&PropertyAnimation_0, delay + 0);
    lv_anim_set_deleted_cb(&PropertyAnimation_0, _ui_anim_callback_free_user_data);
    lv_anim_set_playback_time(&PropertyAnimation_0, 0);
    lv_anim_set_playback_delay(&PropertyAnimation_0, 0);
    lv_anim_set_repeat_count(&PropertyAnimation_0, 3);
    lv_anim_set_repeat_delay(&PropertyAnimation_0, 0);
    lv_anim_set_early_apply(&PropertyAnimation_0, false);
    lv_anim_set_get_value_cb(&PropertyAnimation_0, &_ui_anim_callback_get_image_angle);
    lv_anim_start(&PropertyAnimation_0);

}
void ani_rb0_Animation(lv_obj_t * TargetObject, int delay)
{
    ui_anim_user_data_t * PropertyAnimation_0_user_data = lv_mem_alloc(sizeof(ui_anim_user_data_t));
    PropertyAnimation_0_user_data->target = TargetObject;
    PropertyAnimation_0_user_data->val = -1;
    lv_anim_t PropertyAnimation_0;
    lv_anim_init(&PropertyAnimation_0);
    lv_anim_set_time(&PropertyAnimation_0, 1000);
    lv_anim_set_user_data(&PropertyAnimation_0, PropertyAnimation_0_user_data);
    lv_anim_set_custom_exec_cb(&PropertyAnimation_0, _ui_anim_callback_set_image_angle);
    lv_anim_set_values(&PropertyAnimation_0, 3600, 0);
    lv_anim_set_path_cb(&PropertyAnimation_0, lv_anim_path_linear);
    lv_anim_set_delay(&PropertyAnimation_0, delay + 0);
    lv_anim_set_deleted_cb(&PropertyAnimation_0, _ui_anim_callback_free_user_data);
    lv_anim_set_playback_time(&PropertyAnimation_0, 0);
    lv_anim_set_playback_delay(&PropertyAnimation_0, 0);
    lv_anim_set_repeat_count(&PropertyAnimation_0, 3);
    lv_anim_set_repeat_delay(&PropertyAnimation_0, 0);
    lv_anim_set_early_apply(&PropertyAnimation_0, false);
    lv_anim_set_get_value_cb(&PropertyAnimation_0, &_ui_anim_callback_get_image_angle);
    lv_anim_start(&PropertyAnimation_0);

}
void ani_gold_Animation(lv_obj_t * TargetObject, int delay)
{
    ui_anim_user_data_t * PropertyAnimation_0_user_data = lv_mem_alloc(sizeof(ui_anim_user_data_t));
    PropertyAnimation_0_user_data->target = TargetObject;
    PropertyAnimation_0_user_data->val = -1;
    lv_anim_t PropertyAnimation_0;
    lv_anim_init(&PropertyAnimation_0);
    lv_anim_set_time(&PropertyAnimation_0, 1000);
    lv_anim_set_user_data(&PropertyAnimation_0, PropertyAnimation_0_user_data);
    lv_anim_set_custom_exec_cb(&PropertyAnimation_0, _ui_anim_callback_set_image_angle);
    lv_anim_set_values(&PropertyAnimation_0, 0, 3600);
    lv_anim_set_path_cb(&PropertyAnimation_0, lv_anim_path_linear);
    lv_anim_set_delay(&PropertyAnimation_0, delay + 0);
    lv_anim_set_deleted_cb(&PropertyAnimation_0, _ui_anim_callback_free_user_data);
    lv_anim_set_playback_time(&PropertyAnimation_0, 0);
    lv_anim_set_playback_delay(&PropertyAnimation_0, 0);
    lv_anim_set_repeat_count(&PropertyAnimation_0, 3);
    lv_anim_set_repeat_delay(&PropertyAnimation_0, 0);
    lv_anim_set_early_apply(&PropertyAnimation_0, false);
    lv_anim_set_get_value_cb(&PropertyAnimation_0, &_ui_anim_callback_get_image_angle);
    lv_anim_start(&PropertyAnimation_0);

}
void ani_reddot_Animation(lv_obj_t * TargetObject, int delay)
{
    ui_anim_user_data_t * PropertyAnimation_0_user_data = lv_mem_alloc(sizeof(ui_anim_user_data_t));
    PropertyAnimation_0_user_data->target = TargetObject;
    PropertyAnimation_0_user_data->val = -1;
    lv_anim_t PropertyAnimation_0;
    lv_anim_init(&PropertyAnimation_0);
    lv_anim_set_time(&PropertyAnimation_0, 1000);
    lv_anim_set_user_data(&PropertyAnimation_0, PropertyAnimation_0_user_data);
    lv_anim_set_custom_exec_cb(&PropertyAnimation_0, _ui_anim_callback_set_image_angle);
    lv_anim_set_values(&PropertyAnimation_0, 0, 3600);
    lv_anim_set_path_cb(&PropertyAnimation_0, lv_anim_path_linear);
    lv_anim_set_delay(&PropertyAnimation_0, delay + 0);
    lv_anim_set_deleted_cb(&PropertyAnimation_0, _ui_anim_callback_free_user_data);
    lv_anim_set_playback_time(&PropertyAnimation_0, 0);
    lv_anim_set_playback_delay(&PropertyAnimation_0, 0);
    lv_anim_set_repeat_count(&PropertyAnimation_0, 3);
    lv_anim_set_repeat_delay(&PropertyAnimation_0, 0);
    lv_anim_set_early_apply(&PropertyAnimation_0, false);
    lv_anim_set_get_value_cb(&PropertyAnimation_0, &_ui_anim_callback_get_image_angle);
    lv_anim_start(&PropertyAnimation_0);

}

///////////////////// FUNCTIONS ////////////////////
void ui_event_Screen0(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_SCREEN_LOADED) {
        ani_rb1_Animation(ui_s0rb1, 0);
        ani_rb0_Animation(ui_s0rb0, 0);
        ani_gold_Animation(ui_s0gold, 0);
    }
}
void ui_event_s2btn1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_image_set_property(ui_s2bar2, _UI_IMAGE_PROPERTY_ANGLE, & TemporaryImage);
    }
}
void ui_event_s2btn2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_image_set_property(ui_s2bar2, _UI_IMAGE_PROPERTY_ANGLE, & TemporaryImage);
    }
}
void ui_event_s2btn3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen1, LV_SCR_LOAD_ANIM_FADE_ON, 300, 0, &ui_Screen1_screen_init);
    }
}
void ui_event_s3btn1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_image_set_property(ui_s3bar2, _UI_IMAGE_PROPERTY_ANGLE, & TemporaryImage);
    }
}
void ui_event_s3btn2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_image_set_property(ui_s3bar2, _UI_IMAGE_PROPERTY_ANGLE, & TemporaryImage);
    }
}
void ui_event_s3btn3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen1, LV_SCR_LOAD_ANIM_FADE_ON, 300, 0, &ui_Screen1_screen_init);
    }
}
void ui_event_s4btn1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_image_set_property(ui_s4bar2, _UI_IMAGE_PROPERTY_ANGLE, & TemporaryImage);
    }
}
void ui_event_s4btn2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_image_set_property(ui_s4bar2, _UI_IMAGE_PROPERTY_ANGLE, & TemporaryImage);
    }
}
void ui_event_s4btn3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen1, LV_SCR_LOAD_ANIM_FADE_ON, 300, 0, &ui_Screen1_screen_init);
    }
}

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    LV_EVENT_GET_COMP_CHILD = lv_event_register_id();

    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               false, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_Screen0_screen_init();
    ui_Screen1_screen_init();
    ui_Screen2_screen_init();
    ui_Screen3_screen_init();
    ui_Screen4_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_Screen0);
}
