// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.3
// Project name: SLS480v2

#ifndef _SLS480V2_UI_H
#define _SLS480V2_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_comp.h"
#include "ui_comp_hook.h"
#include "ui_events.h"
void ani_rb1_Animation(lv_obj_t * TargetObject, int delay);
void ani_rb0_Animation(lv_obj_t * TargetObject, int delay);
void ani_gold_Animation(lv_obj_t * TargetObject, int delay);
void ani_reddot_Animation(lv_obj_t * TargetObject, int delay);
// SCREEN: ui_Screen0
void ui_Screen0_screen_init(void);
void ui_event_Screen0(lv_event_t * e);
extern lv_obj_t * ui_Screen0;
extern lv_obj_t * ui_s0rb1;
extern lv_obj_t * ui_s0rb0;
extern lv_obj_t * ui_s0brown;
extern lv_obj_t * ui_s0gold;
// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_s1select;
extern lv_obj_t * ui_s1volume1;
extern lv_obj_t * ui_s1volume2;
extern lv_obj_t * ui_s1lbvolume;
extern lv_obj_t * ui_s1temp1;
extern lv_obj_t * ui_s1temp2;
extern lv_obj_t * ui_s1lbtemp;
extern lv_obj_t * ui_s1light1;
extern lv_obj_t * ui_s1light2;
extern lv_obj_t * ui_s1lblight;
// SCREEN: ui_Screen2
void ui_Screen2_screen_init(void);
extern lv_obj_t * ui_Screen2;
void ui_event_s2btn1(lv_event_t * e);
extern lv_obj_t * ui_s2btn1;
extern lv_obj_t * ui_s2lbbtn1;
void ui_event_s2btn2(lv_event_t * e);
extern lv_obj_t * ui_s2btn2;
extern lv_obj_t * ui_s2lbbtn2;
void ui_event_s2btn3(lv_event_t * e);
extern lv_obj_t * ui_s2btn3;
extern lv_obj_t * ui_s2lbbtn3;
extern lv_obj_t * ui_s2Container;
extern lv_obj_t * ui_s2bar1;
extern lv_obj_t * ui_s2bar2;
extern lv_obj_t * ui_s2arc;
extern lv_obj_t * ui_s2icon;
extern lv_obj_t * ui_s2volume;
extern lv_obj_t * ui_s2num1;
extern lv_obj_t * ui_s2num2;
extern lv_obj_t * ui_s2num0;
extern lv_obj_t * ui_s2num10;
extern lv_obj_t * ui_s2num20;
extern lv_obj_t * ui_s2num30;
extern lv_obj_t * ui_s2num40;
extern lv_obj_t * ui_s2num50;
extern lv_obj_t * ui_s2num60;
extern lv_obj_t * ui_s2num70;
extern lv_obj_t * ui_s2num80;
extern lv_obj_t * ui_s2num90;
extern lv_obj_t * ui_s2num100;
// SCREEN: ui_Screen3
void ui_Screen3_screen_init(void);
extern lv_obj_t * ui_Screen3;
void ui_event_s3btn1(lv_event_t * e);
extern lv_obj_t * ui_s3btn1;
extern lv_obj_t * ui_s3lbbtn1;
void ui_event_s3btn2(lv_event_t * e);
extern lv_obj_t * ui_s3btn2;
extern lv_obj_t * ui_s3lbbtn2;
void ui_event_s3btn3(lv_event_t * e);
extern lv_obj_t * ui_s3btn3;
extern lv_obj_t * ui_s3lbbtn3;
extern lv_obj_t * ui_s3Container;
extern lv_obj_t * ui_s3bar1;
extern lv_obj_t * ui_s3bar2;
extern lv_obj_t * ui_s3arc;
extern lv_obj_t * ui_s3icon;
extern lv_obj_t * ui_s3temp;
extern lv_obj_t * ui_s3num1;
extern lv_obj_t * ui_s3num2;
extern lv_obj_t * ui_s3num0;
extern lv_obj_t * ui_s3num10;
extern lv_obj_t * ui_s3num20;
extern lv_obj_t * ui_s3num30;
extern lv_obj_t * ui_s3num40;
extern lv_obj_t * ui_s3num50;
extern lv_obj_t * ui_s3num60;
extern lv_obj_t * ui_s3num70;
extern lv_obj_t * ui_s3num80;
extern lv_obj_t * ui_s3num90;
extern lv_obj_t * ui_s3num100;
// SCREEN: ui_Screen4
void ui_Screen4_screen_init(void);
extern lv_obj_t * ui_Screen4;
void ui_event_s4btn1(lv_event_t * e);
extern lv_obj_t * ui_s4btn1;
extern lv_obj_t * ui_s4lbbtn1;
void ui_event_s4btn2(lv_event_t * e);
extern lv_obj_t * ui_s4btn2;
extern lv_obj_t * ui_s4lbbtn2;
void ui_event_s4btn3(lv_event_t * e);
extern lv_obj_t * ui_s4btn3;
extern lv_obj_t * ui_s4lbbtn3;
extern lv_obj_t * ui_s4Container;
extern lv_obj_t * ui_s4bar1;
extern lv_obj_t * ui_s4bar2;
extern lv_obj_t * ui_s4arc;
extern lv_obj_t * ui_s4icon;
extern lv_obj_t * ui_s4light;
extern lv_obj_t * ui_s4num1;
extern lv_obj_t * ui_s4num2;
extern lv_obj_t * ui_s4num0;
extern lv_obj_t * ui_s4num10;
extern lv_obj_t * ui_s4num20;
extern lv_obj_t * ui_s4num30;
extern lv_obj_t * ui_s4num40;
extern lv_obj_t * ui_s4num50;
extern lv_obj_t * ui_s4num60;
extern lv_obj_t * ui_s4num70;
extern lv_obj_t * ui_s4num80;
extern lv_obj_t * ui_s4num90;
extern lv_obj_t * ui_s4num100;
extern lv_obj_t * ui____initial_actions0;

LV_IMG_DECLARE(ui_img_s0rb1_png);    // assets\s0rb1.png
LV_IMG_DECLARE(ui_img_s0rb0_png);    // assets\s0rb0.png
LV_IMG_DECLARE(ui_img_s0brown_png);    // assets\s0brown.png
LV_IMG_DECLARE(ui_img_s0gold_png);    // assets\s0gold.png
LV_IMG_DECLARE(ui_img_s1bg_png);    // assets\s1bg.png
LV_IMG_DECLARE(ui_img_s1select_png);    // assets\s1select.png
LV_IMG_DECLARE(ui_img_s1volume1_png);    // assets\s1volume1.png
LV_IMG_DECLARE(ui_img_s1volume2_png);    // assets\s1volume2.png
LV_IMG_DECLARE(ui_img_s1temp1_png);    // assets\s1temp1.png
LV_IMG_DECLARE(ui_img_s1temp2_png);    // assets\s1temp2.png
LV_IMG_DECLARE(ui_img_s1light1_png);    // assets\s1light1.png
LV_IMG_DECLARE(ui_img_s1light2_png);    // assets\s1light2.png
LV_IMG_DECLARE(ui_img_v2_bj_volume_png);    // assets\v2_bj_volume.png
LV_IMG_DECLARE(ui_img_bar_blue_png);    // assets\bar_blue.png
LV_IMG_DECLARE(ui_img_bar_white_png);    // assets\bar_white.png
LV_IMG_DECLARE(ui_img_s2icon_png);    // assets\s2icon.png
LV_IMG_DECLARE(ui_img_v2_bj_temp_png);    // assets\v2_bj_temp.png
LV_IMG_DECLARE(ui_img_bar_orange_png);    // assets\bar_orange.png
LV_IMG_DECLARE(ui_img_bar_black_png);    // assets\bar_black.png
LV_IMG_DECLARE(ui_img_s3icon_png);    // assets\s3icon.png
LV_IMG_DECLARE(ui_img_v2_bj_light_png);    // assets\v2_bj_light.png
LV_IMG_DECLARE(ui_img_bar_yellow_png);    // assets\bar_yellow.png
LV_IMG_DECLARE(ui_img_s4icon_png);    // assets\s4icon.png
LV_IMG_DECLARE(ui_img_to128_s1light1_png);    // assets\to128\s1light1.png
LV_IMG_DECLARE(ui_img_to128_s1light2_png);    // assets\to128\s1light2.png
LV_IMG_DECLARE(ui_img_to128_s1temp1_png);    // assets\to128\s1temp1.png
LV_IMG_DECLARE(ui_img_to128_s1temp2_png);    // assets\to128\s1temp2.png
LV_IMG_DECLARE(ui_img_to128_s1volume1_png);    // assets\to128\s1volume1.png
LV_IMG_DECLARE(ui_img_to128_s1volume2_png);    // assets\to128\s1volume2.png



void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
