// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.3
// Project name: SLS480v2

#include "ui.h"

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Screen1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_Screen1, &ui_img_s1bg_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_s1select = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_s1select, &ui_img_s1select_png);
    lv_obj_set_width(ui_s1select, LV_SIZE_CONTENT);   /// 70
    lv_obj_set_height(ui_s1select, LV_SIZE_CONTENT);    /// 200
    lv_obj_set_align(ui_s1select, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_s1select, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags

    ui_s1volume1 = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_s1volume1, &ui_img_s1volume1_png);
    lv_obj_set_width(ui_s1volume1, 60);
    lv_obj_set_height(ui_s1volume1, 60);
    lv_obj_set_x(ui_s1volume1, -140);
    lv_obj_set_y(ui_s1volume1, -20);
    lv_obj_set_align(ui_s1volume1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_s1volume1, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_clear_flag(ui_s1volume1, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags

    ui_s1volume2 = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_s1volume2, &ui_img_s1volume2_png);
    lv_obj_set_width(ui_s1volume2, 60);
    lv_obj_set_height(ui_s1volume2, 60);
    lv_obj_set_x(ui_s1volume2, 0);
    lv_obj_set_y(ui_s1volume2, -20);
    lv_obj_set_align(ui_s1volume2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_s1volume2, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_clear_flag(ui_s1volume2, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags

    ui_s1lbvolume = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_s1lbvolume, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_s1lbvolume, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_s1lbvolume, -140);
    lv_obj_set_y(ui_s1lbvolume, 30);
    lv_obj_set_align(ui_s1lbvolume, LV_ALIGN_CENTER);
    lv_label_set_text(ui_s1lbvolume, "Oven");
    lv_obj_add_flag(ui_s1lbvolume, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_clear_flag(ui_s1lbvolume, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_s1lbvolume, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_s1lbvolume, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_s1lbvolume, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_s1lbvolume, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_s1temp1 = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_s1temp1, &ui_img_s1temp1_png);
    lv_obj_set_width(ui_s1temp1, 60);
    lv_obj_set_height(ui_s1temp1, 60);
    lv_obj_set_x(ui_s1temp1, 0);
    lv_obj_set_y(ui_s1temp1, -20);
    lv_obj_set_align(ui_s1temp1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_s1temp1, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_clear_flag(ui_s1temp1, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags

    ui_s1temp2 = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_s1temp2, &ui_img_s1temp2_png);
    lv_obj_set_width(ui_s1temp2, 60);
    lv_obj_set_height(ui_s1temp2, 60);
    lv_obj_set_x(ui_s1temp2, 0);
    lv_obj_set_y(ui_s1temp2, -20);
    lv_obj_set_align(ui_s1temp2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_s1temp2, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_clear_flag(ui_s1temp2, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags

    ui_s1lbtemp = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_s1lbtemp, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_s1lbtemp, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_s1lbtemp, 0);
    lv_obj_set_y(ui_s1lbtemp, 41);
    lv_obj_set_align(ui_s1lbtemp, LV_ALIGN_CENTER);
    lv_label_set_text(ui_s1lbtemp, "Washing\nMachine");
    lv_obj_add_flag(ui_s1lbtemp, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_clear_flag(ui_s1lbtemp, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_s1lbtemp, lv_color_hex(0x00FFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_s1lbtemp, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_s1lbtemp, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_s1lbtemp, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_s1light1 = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_s1light1, &ui_img_s1light1_png);
    lv_obj_set_width(ui_s1light1, 60);
    lv_obj_set_height(ui_s1light1, 60);
    lv_obj_set_x(ui_s1light1, 140);
    lv_obj_set_y(ui_s1light1, -20);
    lv_obj_set_align(ui_s1light1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_s1light1, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_clear_flag(ui_s1light1, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags

    ui_s1light2 = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_s1light2, &ui_img_s1light2_png);
    lv_obj_set_width(ui_s1light2, 60);
    lv_obj_set_height(ui_s1light2, 60);
    lv_obj_set_x(ui_s1light2, 0);
    lv_obj_set_y(ui_s1light2, -20);
    lv_obj_set_align(ui_s1light2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_s1light2, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_clear_flag(ui_s1light2, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags

    ui_s1lblight = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_s1lblight, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_s1lblight, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_s1lblight, 140);
    lv_obj_set_y(ui_s1lblight, 30);
    lv_obj_set_align(ui_s1lblight, LV_ALIGN_CENTER);
    lv_label_set_text(ui_s1lblight, "Light");
    lv_obj_add_flag(ui_s1lblight, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_clear_flag(ui_s1lblight, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_s1lblight, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_s1lblight, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_s1lblight, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_s1lblight, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

}
