// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.3
// Project name: SLS480v2

#include "ui.h"

void ui_Screen2_screen_init(void)
{
    ui_Screen2 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Screen2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_Screen2, &ui_img_v2_bj_volume_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_s2btn1 = lv_btn_create(ui_Screen2);
    lv_obj_set_width(ui_s2btn1, 125);
    lv_obj_set_height(ui_s2btn1, 42);
    lv_obj_set_x(ui_s2btn1, -70);
    lv_obj_set_y(ui_s2btn1, 120);
    lv_obj_set_align(ui_s2btn1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_s2btn1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_s2btn1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_s2btn1, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_s2btn1, lv_color_hex(0x33DCFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_s2btn1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_s2lbbtn1 = lv_label_create(ui_s2btn1);
    lv_obj_set_width(ui_s2lbbtn1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_s2lbbtn1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_s2lbbtn1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_s2lbbtn1, "-");
    lv_obj_set_style_text_color(ui_s2lbbtn1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_s2lbbtn1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_s2lbbtn1, &lv_font_montserrat_40, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_s2btn2 = lv_btn_create(ui_Screen2);
    lv_obj_set_width(ui_s2btn2, 125);
    lv_obj_set_height(ui_s2btn2, 42);
    lv_obj_set_x(ui_s2btn2, 70);
    lv_obj_set_y(ui_s2btn2, 120);
    lv_obj_set_align(ui_s2btn2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_s2btn2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_s2btn2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_s2btn2, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_s2btn2, lv_color_hex(0xFFD400), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_s2btn2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_s2lbbtn2 = lv_label_create(ui_s2btn2);
    lv_obj_set_width(ui_s2lbbtn2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_s2lbbtn2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_s2lbbtn2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_s2lbbtn2, "+");
    lv_obj_set_style_text_color(ui_s2lbbtn2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_s2lbbtn2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_s2lbbtn2, &lv_font_montserrat_40, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_s2btn3 = lv_btn_create(ui_Screen2);
    lv_obj_set_width(ui_s2btn3, 125);
    lv_obj_set_height(ui_s2btn3, 42);
    lv_obj_set_x(ui_s2btn3, 0);
    lv_obj_set_y(ui_s2btn3, 180);
    lv_obj_set_align(ui_s2btn3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_s2btn3, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_s2btn3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_s2btn3, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_s2btn3, lv_color_hex(0x33DCFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_s2btn3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_s2lbbtn3 = lv_label_create(ui_s2btn3);
    lv_obj_set_width(ui_s2lbbtn3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_s2lbbtn3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_s2lbbtn3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_s2lbbtn3, "Return");
    lv_obj_set_style_text_color(ui_s2lbbtn3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_s2lbbtn3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_s2lbbtn3, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_s2Container = lv_obj_create(ui_Screen2);
    lv_obj_remove_style_all(ui_s2Container);
    lv_obj_set_width(ui_s2Container, 340);
    lv_obj_set_height(ui_s2Container, 266);
    lv_obj_set_x(ui_s2Container, 0);
    lv_obj_set_y(ui_s2Container, -40);
    lv_obj_set_align(ui_s2Container, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_s2Container, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_s2bar1 = lv_img_create(ui_s2Container);
    lv_img_set_src(ui_s2bar1, &ui_img_bar_blue_png);
    lv_obj_set_width(ui_s2bar1, 340);
    lv_obj_set_height(ui_s2bar1, 270);
    lv_obj_set_align(ui_s2bar1, LV_ALIGN_TOP_MID);
    lv_obj_add_flag(ui_s2bar1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_s2bar1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_s2bar2 = lv_img_create(ui_s2Container);
    lv_img_set_src(ui_s2bar2, &ui_img_bar_white_png);
    lv_obj_set_width(ui_s2bar2, 340);
    lv_obj_set_height(ui_s2bar2, 270);
    lv_obj_set_align(ui_s2bar2, LV_ALIGN_TOP_MID);
    lv_obj_add_flag(ui_s2bar2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_s2bar2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_s2arc = lv_arc_create(ui_s2Container);
    lv_obj_set_width(ui_s2arc, 332);
    lv_obj_set_height(ui_s2arc, 332);
    lv_obj_set_x(ui_s2arc, 0);
    lv_obj_set_y(ui_s2arc, 4);
    lv_obj_set_align(ui_s2arc, LV_ALIGN_TOP_MID);
    lv_arc_set_bg_angles(ui_s2arc, 147, 33);


    ui_s2icon = lv_img_create(ui_Screen2);
    lv_img_set_src(ui_s2icon, &ui_img_s2icon_png);
    lv_obj_set_width(ui_s2icon, LV_SIZE_CONTENT);   /// 40
    lv_obj_set_height(ui_s2icon, LV_SIZE_CONTENT);    /// 40
    lv_obj_set_x(ui_s2icon, 0);
    lv_obj_set_y(ui_s2icon, -80);
    lv_obj_set_align(ui_s2icon, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_s2icon, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_s2icon, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_s2volume = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_s2volume, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_s2volume, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_s2volume, 0);
    lv_obj_set_y(ui_s2volume, 60);
    lv_obj_set_align(ui_s2volume, LV_ALIGN_CENTER);
    lv_label_set_text(ui_s2volume, "Volume");
    lv_obj_set_style_text_color(ui_s2volume, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_s2volume, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_s2volume, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_s2num1 = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_s2num1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_s2num1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_s2num1, -24);
    lv_obj_set_y(ui_s2num1, -5);
    lv_obj_set_align(ui_s2num1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_s2num1, "55");
    lv_obj_set_style_text_color(ui_s2num1, lv_color_hex(0x33DCFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_s2num1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_s2num1, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_s2num2 = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_s2num2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_s2num2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_s2num2, 24);
    lv_obj_set_y(ui_s2num2, -5);
    lv_obj_set_align(ui_s2num2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_s2num2, "%");
    lv_obj_set_style_text_color(ui_s2num2, lv_color_hex(0x33DCFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_s2num2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_s2num2, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_s2num0 = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_s2num0, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_s2num0, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_s2num0, -159);
    lv_obj_set_y(ui_s2num0, 108);
    lv_obj_set_align(ui_s2num0, LV_ALIGN_CENTER);
    lv_label_set_text(ui_s2num0, "0%");
    lv_obj_set_style_text_color(ui_s2num0, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_s2num0, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_s2num0, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_s2num10 = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_s2num10, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_s2num10, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_s2num10, -192);
    lv_obj_set_y(ui_s2num10, 34);
    lv_obj_set_align(ui_s2num10, LV_ALIGN_CENTER);
    lv_label_set_text(ui_s2num10, "10");
    lv_obj_set_style_text_color(ui_s2num10, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_s2num10, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_s2num10, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_s2num20 = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_s2num20, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_s2num20, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_s2num20, -189);
    lv_obj_set_y(ui_s2num20, -49);
    lv_obj_set_align(ui_s2num20, LV_ALIGN_CENTER);
    lv_label_set_text(ui_s2num20, "20");
    lv_obj_set_style_text_color(ui_s2num20, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_s2num20, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_s2num20, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_s2num30 = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_s2num30, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_s2num30, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_s2num30, -152);
    lv_obj_set_y(ui_s2num30, -126);
    lv_obj_set_align(ui_s2num30, LV_ALIGN_CENTER);
    lv_label_set_text(ui_s2num30, "30");
    lv_obj_set_style_text_color(ui_s2num30, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_s2num30, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_s2num30, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_s2num40 = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_s2num40, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_s2num40, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_s2num40, -85);
    lv_obj_set_y(ui_s2num40, -178);
    lv_obj_set_align(ui_s2num40, LV_ALIGN_CENTER);
    lv_label_set_text(ui_s2num40, "40");
    lv_obj_set_style_text_color(ui_s2num40, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_s2num40, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_s2num40, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_s2num50 = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_s2num50, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_s2num50, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_s2num50, -2);
    lv_obj_set_y(ui_s2num50, -198);
    lv_obj_set_align(ui_s2num50, LV_ALIGN_CENTER);
    lv_label_set_text(ui_s2num50, "50");
    lv_obj_set_style_text_color(ui_s2num50, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_s2num50, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_s2num50, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_s2num60 = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_s2num60, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_s2num60, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_s2num60, 75);
    lv_obj_set_y(ui_s2num60, -181);
    lv_obj_set_align(ui_s2num60, LV_ALIGN_CENTER);
    lv_label_set_text(ui_s2num60, "60");
    lv_obj_set_style_text_color(ui_s2num60, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_s2num60, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_s2num60, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_s2num70 = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_s2num70, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_s2num70, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_s2num70, 145);
    lv_obj_set_y(ui_s2num70, -134);
    lv_obj_set_align(ui_s2num70, LV_ALIGN_CENTER);
    lv_label_set_text(ui_s2num70, "70");
    lv_obj_set_style_text_color(ui_s2num70, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_s2num70, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_s2num70, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_s2num80 = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_s2num80, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_s2num80, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_s2num80, 188);
    lv_obj_set_y(ui_s2num80, -58);
    lv_obj_set_align(ui_s2num80, LV_ALIGN_CENTER);
    lv_label_set_text(ui_s2num80, "80");
    lv_obj_set_style_text_color(ui_s2num80, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_s2num80, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_s2num80, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_s2num90 = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_s2num90, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_s2num90, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_s2num90, 194);
    lv_obj_set_y(ui_s2num90, 27);
    lv_obj_set_align(ui_s2num90, LV_ALIGN_CENTER);
    lv_label_set_text(ui_s2num90, "90");
    lv_obj_set_style_text_color(ui_s2num90, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_s2num90, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_s2num90, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_s2num100 = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_s2num100, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_s2num100, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_s2num100, 162);
    lv_obj_set_y(ui_s2num100, 108);
    lv_obj_set_align(ui_s2num100, LV_ALIGN_CENTER);
    lv_label_set_text(ui_s2num100, "100");
    lv_obj_set_style_text_color(ui_s2num100, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_s2num100, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_s2num100, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_s2btn1, ui_event_s2btn1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_s2btn2, ui_event_s2btn2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_s2btn3, ui_event_s2btn3, LV_EVENT_ALL, NULL);

}
