// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.3
// Project name: SLS480v2

#include "ui.h"

void ui_Screen4_screen_init(void)
{
    ui_Screen4 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Screen4, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_Screen4, &ui_img_v2_bj_light_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_s4btn1 = lv_btn_create(ui_Screen4);
    lv_obj_set_width(ui_s4btn1, 125);
    lv_obj_set_height(ui_s4btn1, 42);
    lv_obj_set_x(ui_s4btn1, -70);
    lv_obj_set_y(ui_s4btn1, 120);
    lv_obj_set_align(ui_s4btn1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_s4btn1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_s4btn1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_s4btn1, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_s4btn1, lv_color_hex(0x33DCFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_s4btn1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_s4lbbtn1 = lv_label_create(ui_s4btn1);
    lv_obj_set_width(ui_s4lbbtn1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_s4lbbtn1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_s4lbbtn1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_s4lbbtn1, "Stop");
    lv_obj_set_style_text_color(ui_s4lbbtn1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_s4lbbtn1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_s4lbbtn1, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_s4btn2 = lv_btn_create(ui_Screen4);
    lv_obj_set_width(ui_s4btn2, 125);
    lv_obj_set_height(ui_s4btn2, 42);
    lv_obj_set_x(ui_s4btn2, 70);
    lv_obj_set_y(ui_s4btn2, 120);
    lv_obj_set_align(ui_s4btn2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_s4btn2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_s4btn2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_s4btn2, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_s4btn2, lv_color_hex(0xFFD400), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_s4btn2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_s4lbbtn2 = lv_label_create(ui_s4btn2);
    lv_obj_set_width(ui_s4lbbtn2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_s4lbbtn2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_s4lbbtn2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_s4lbbtn2, "Keep on");
    lv_obj_set_style_text_color(ui_s4lbbtn2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_s4lbbtn2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_s4lbbtn2, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_s4btn3 = lv_btn_create(ui_Screen4);
    lv_obj_set_width(ui_s4btn3, 125);
    lv_obj_set_height(ui_s4btn3, 42);
    lv_obj_set_x(ui_s4btn3, 0);
    lv_obj_set_y(ui_s4btn3, 180);
    lv_obj_set_align(ui_s4btn3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_s4btn3, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_s4btn3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_s4btn3, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_s4btn3, lv_color_hex(0x33DCFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_s4btn3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_s4lbbtn3 = lv_label_create(ui_s4btn3);
    lv_obj_set_width(ui_s4lbbtn3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_s4lbbtn3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_s4lbbtn3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_s4lbbtn3, "Return");
    lv_obj_set_style_text_color(ui_s4lbbtn3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_s4lbbtn3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_s4lbbtn3, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_s4Container = lv_obj_create(ui_Screen4);
    lv_obj_remove_style_all(ui_s4Container);
    lv_obj_set_width(ui_s4Container, 340);
    lv_obj_set_height(ui_s4Container, 266);
    lv_obj_set_x(ui_s4Container, 0);
    lv_obj_set_y(ui_s4Container, -40);
    lv_obj_set_align(ui_s4Container, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_s4Container, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_s4bar1 = lv_img_create(ui_s4Container);
    lv_img_set_src(ui_s4bar1, &ui_img_bar_yellow_png);
    lv_obj_set_width(ui_s4bar1, 340);
    lv_obj_set_height(ui_s4bar1, 270);
    lv_obj_set_align(ui_s4bar1, LV_ALIGN_TOP_MID);
    lv_obj_add_flag(ui_s4bar1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_s4bar1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_s4bar2 = lv_img_create(ui_s4Container);
    lv_img_set_src(ui_s4bar2, &ui_img_bar_white_png);
    lv_obj_set_width(ui_s4bar2, 340);
    lv_obj_set_height(ui_s4bar2, 270);
    lv_obj_set_align(ui_s4bar2, LV_ALIGN_TOP_MID);
    lv_obj_add_flag(ui_s4bar2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_s4bar2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_s4arc = lv_arc_create(ui_s4Container);
    lv_obj_set_width(ui_s4arc, 332);
    lv_obj_set_height(ui_s4arc, 332);
    lv_obj_set_x(ui_s4arc, 0);
    lv_obj_set_y(ui_s4arc, 4);
    lv_obj_set_align(ui_s4arc, LV_ALIGN_TOP_MID);
    lv_arc_set_bg_angles(ui_s4arc, 147, 33);


    ui_s4icon = lv_img_create(ui_Screen4);
    lv_img_set_src(ui_s4icon, &ui_img_s4icon_png);
    lv_obj_set_width(ui_s4icon, LV_SIZE_CONTENT);   /// 40
    lv_obj_set_height(ui_s4icon, LV_SIZE_CONTENT);    /// 40
    lv_obj_set_x(ui_s4icon, 0);
    lv_obj_set_y(ui_s4icon, -80);
    lv_obj_set_align(ui_s4icon, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_s4icon, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_s4icon, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_s4light = lv_label_create(ui_Screen4);
    lv_obj_set_width(ui_s4light, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_s4light, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_s4light, 0);
    lv_obj_set_y(ui_s4light, 60);
    lv_obj_set_align(ui_s4light, LV_ALIGN_CENTER);
    lv_label_set_text(ui_s4light, "Light");
    lv_obj_set_style_text_color(ui_s4light, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_s4light, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_s4light, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_s4num1 = lv_label_create(ui_Screen4);
    lv_obj_set_width(ui_s4num1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_s4num1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_s4num1, -24);
    lv_obj_set_y(ui_s4num1, -5);
    lv_obj_set_align(ui_s4num1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_s4num1, "55");
    lv_obj_set_style_text_color(ui_s4num1, lv_color_hex(0xFFD400), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_s4num1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_s4num1, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_s4num2 = lv_label_create(ui_Screen4);
    lv_obj_set_width(ui_s4num2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_s4num2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_s4num2, 24);
    lv_obj_set_y(ui_s4num2, -5);
    lv_obj_set_align(ui_s4num2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_s4num2, "%");
    lv_obj_set_style_text_color(ui_s4num2, lv_color_hex(0xFFD400), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_s4num2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_s4num2, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_s4num0 = lv_label_create(ui_Screen4);
    lv_obj_set_width(ui_s4num0, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_s4num0, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_s4num0, -159);
    lv_obj_set_y(ui_s4num0, 108);
    lv_obj_set_align(ui_s4num0, LV_ALIGN_CENTER);
    lv_label_set_text(ui_s4num0, "0%");
    lv_obj_set_style_text_color(ui_s4num0, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_s4num0, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_s4num0, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_s4num10 = lv_label_create(ui_Screen4);
    lv_obj_set_width(ui_s4num10, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_s4num10, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_s4num10, -192);
    lv_obj_set_y(ui_s4num10, 34);
    lv_obj_set_align(ui_s4num10, LV_ALIGN_CENTER);
    lv_label_set_text(ui_s4num10, "10");
    lv_obj_set_style_text_color(ui_s4num10, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_s4num10, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_s4num10, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_s4num20 = lv_label_create(ui_Screen4);
    lv_obj_set_width(ui_s4num20, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_s4num20, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_s4num20, -189);
    lv_obj_set_y(ui_s4num20, -49);
    lv_obj_set_align(ui_s4num20, LV_ALIGN_CENTER);
    lv_label_set_text(ui_s4num20, "20");
    lv_obj_set_style_text_color(ui_s4num20, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_s4num20, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_s4num20, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_s4num30 = lv_label_create(ui_Screen4);
    lv_obj_set_width(ui_s4num30, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_s4num30, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_s4num30, -152);
    lv_obj_set_y(ui_s4num30, -126);
    lv_obj_set_align(ui_s4num30, LV_ALIGN_CENTER);
    lv_label_set_text(ui_s4num30, "30");
    lv_obj_set_style_text_color(ui_s4num30, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_s4num30, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_s4num30, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_s4num40 = lv_label_create(ui_Screen4);
    lv_obj_set_width(ui_s4num40, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_s4num40, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_s4num40, -85);
    lv_obj_set_y(ui_s4num40, -178);
    lv_obj_set_align(ui_s4num40, LV_ALIGN_CENTER);
    lv_label_set_text(ui_s4num40, "40");
    lv_obj_set_style_text_color(ui_s4num40, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_s4num40, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_s4num40, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_s4num50 = lv_label_create(ui_Screen4);
    lv_obj_set_width(ui_s4num50, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_s4num50, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_s4num50, -2);
    lv_obj_set_y(ui_s4num50, -198);
    lv_obj_set_align(ui_s4num50, LV_ALIGN_CENTER);
    lv_label_set_text(ui_s4num50, "50");
    lv_obj_set_style_text_color(ui_s4num50, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_s4num50, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_s4num50, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_s4num60 = lv_label_create(ui_Screen4);
    lv_obj_set_width(ui_s4num60, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_s4num60, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_s4num60, 75);
    lv_obj_set_y(ui_s4num60, -181);
    lv_obj_set_align(ui_s4num60, LV_ALIGN_CENTER);
    lv_label_set_text(ui_s4num60, "60");
    lv_obj_set_style_text_color(ui_s4num60, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_s4num60, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_s4num60, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_s4num70 = lv_label_create(ui_Screen4);
    lv_obj_set_width(ui_s4num70, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_s4num70, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_s4num70, 145);
    lv_obj_set_y(ui_s4num70, -134);
    lv_obj_set_align(ui_s4num70, LV_ALIGN_CENTER);
    lv_label_set_text(ui_s4num70, "70");
    lv_obj_set_style_text_color(ui_s4num70, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_s4num70, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_s4num70, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_s4num80 = lv_label_create(ui_Screen4);
    lv_obj_set_width(ui_s4num80, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_s4num80, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_s4num80, 188);
    lv_obj_set_y(ui_s4num80, -58);
    lv_obj_set_align(ui_s4num80, LV_ALIGN_CENTER);
    lv_label_set_text(ui_s4num80, "80");
    lv_obj_set_style_text_color(ui_s4num80, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_s4num80, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_s4num80, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_s4num90 = lv_label_create(ui_Screen4);
    lv_obj_set_width(ui_s4num90, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_s4num90, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_s4num90, 194);
    lv_obj_set_y(ui_s4num90, 27);
    lv_obj_set_align(ui_s4num90, LV_ALIGN_CENTER);
    lv_label_set_text(ui_s4num90, "90");
    lv_obj_set_style_text_color(ui_s4num90, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_s4num90, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_s4num90, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_s4num100 = lv_label_create(ui_Screen4);
    lv_obj_set_width(ui_s4num100, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_s4num100, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_s4num100, 162);
    lv_obj_set_y(ui_s4num100, 108);
    lv_obj_set_align(ui_s4num100, LV_ALIGN_CENTER);
    lv_label_set_text(ui_s4num100, "100");
    lv_obj_set_style_text_color(ui_s4num100, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_s4num100, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_s4num100, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_s4btn1, ui_event_s4btn1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_s4btn2, ui_event_s4btn2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_s4btn3, ui_event_s4btn3, LV_EVENT_ALL, NULL);

}
