// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.3
// Project name: SLS480v2

#include "ui.h"

void ui_Screen0_screen_init(void)
{
    ui_Screen0 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen0, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_SCROLLABLE |
                      LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM);     /// Flags
    lv_obj_set_style_bg_color(ui_Screen0, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen0, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_s0rb1 = lv_img_create(ui_Screen0);
    lv_img_set_src(ui_s0rb1, &ui_img_s0rb1_png);
    lv_obj_set_width(ui_s0rb1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_s0rb1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_s0rb1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_s0rb1, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags

    ui_s0rb0 = lv_img_create(ui_Screen0);
    lv_img_set_src(ui_s0rb0, &ui_img_s0rb0_png);
    lv_obj_set_width(ui_s0rb0, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_s0rb0, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_s0rb0, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_s0rb0, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags

    ui_s0brown = lv_img_create(ui_Screen0);
    lv_img_set_src(ui_s0brown, &ui_img_s0brown_png);
    lv_obj_set_width(ui_s0brown, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_s0brown, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_s0brown, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_s0brown, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags

    ui_s0gold = lv_img_create(ui_Screen0);
    lv_img_set_src(ui_s0gold, &ui_img_s0gold_png);
    lv_obj_set_width(ui_s0gold, LV_SIZE_CONTENT);   /// 60
    lv_obj_set_height(ui_s0gold, LV_SIZE_CONTENT);    /// 60
    lv_obj_set_align(ui_s0gold, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_s0gold, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags

    lv_obj_add_event_cb(ui_Screen0, ui_event_Screen0, LV_EVENT_ALL, NULL);

}
